In [2]:
# https://stackoverflow.com/questions/64261546/how-to-solve-error-microsoft-visual-c-14-0-or-greater-is-required-when-inst
# !pip install hnswlib

  Using cached hnswlib-0.6.2.tar.gz (31 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Created wheel for hnswlib: filename=hnswlib-0.6.2-cp39-cp39-win_amd64.whl size=135742 sha256=2eca5754dd5269c60b5fcd0470c0be1dd3056ffb2a817d47c984469358c1e51b
  Stored in directory: c:\users\soiko\appdata\local\pip\cache\wheels\42\ef\fe\bab7e480effd9f1bb90c3dfc354ac1bceb27eb0f7e0877efdc
Successfully built hnswlib


In [1]:
# https://github.com/facebookresearch/faiss/blob/main/INSTALL.md
# conda install -c conda-forge faiss-cpu

Note: you may need to restart the kernel to use updated packages.




==> WARNING: A newer version of conda exists. <==
  current version: 4.14.0
  latest version: 22.9.0

Please update conda by running

    $ conda update -n base -c defaults conda





Solving environment: ...working... done

## Package Plan ##

  environment location: c:\Users\soiko\anaconda3

  added / updated specs:
    - faiss-cpu


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2022.9.24  |       h5b45459_0         189 KB  conda-forge
    certifi-2022.9.24          |     pyhd8ed1ab_0         155 KB  conda-forge
    conda-22.9.0               |   py39hcbf5309_1         968 KB  conda-forge
    faiss-1.7.2                |py39hfccd52d_1_cpu         1.6 MB  conda-forge
    faiss-cpu-1.7.2            |       hf9c7e24_1          15 KB  conda-forge
    libblas-3.9.0              |1_h8933c1f_netlib         193 KB  conda-forge
    libfaiss-1.7.2             |   hba6d9cf_1_cpu         974 KB  conda-forge
    libfaiss-avx2-1.7.2        |   h1234567_1_cpu         985 KB  conda-forge
    liblapack-3.9.0            |5_hd5c7e75_netlib         2.7 MB  conda-forg


m2w64-gcc-libs-core- | 214 KB    |            |   0% 
m2w64-gcc-libs-core- | 214 KB    | 7          |   7% 
m2w64-gcc-libs-core- | 214 KB    | ##2        |  22% 
m2w64-gcc-libs-core- | 214 KB    | #####9     |  60% 
m2w64-gcc-libs-core- | 214 KB    | ########## | 100% 
m2w64-gcc-libs-core- | 214 KB    | ########## | 100% 

m2w64-gmp-6.1.0      | 726 KB    |            |   0% 
m2w64-gmp-6.1.0      | 726 KB    | 2          |   2% 
m2w64-gmp-6.1.0      | 726 KB    | 6          |   7% 
m2w64-gmp-6.1.0      | 726 KB    | #9         |  20% 
m2w64-gmp-6.1.0      | 726 KB    | ##8        |  29% 
m2w64-gmp-6.1.0      | 726 KB    | ###9       |  40% 
m2w64-gmp-6.1.0      | 726 KB    | ####8      |  48% 
m2w64-gmp-6.1.0      | 726 KB    | #####7     |  57% 
m2w64-gmp-6.1.0      | 726 KB    | ######6    |  66% 
m2w64-gmp-6.1.0      | 726 KB    | ########1  |  82% 
m2w64-gmp-6.1.0      | 726 KB    | #########2 |  93% 
m2w64-gmp-6.1.0      | 726 KB    | ########## | 100% 

m2w64-gcc-libs-5.3.0 | 52

In [2]:
conda update -n base -c defaults conda

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\soiko\anaconda3

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    anaconda-client-1.11.0     |   py39haa95532_0         165 KB
    async-timeout-4.0.2        |   py39haa95532_0          12 KB
    blosc-1.21.0               |       h19a0ad4_1         145 KB
    certifi-2022.9.24          |   py39haa95532_0         154 KB
    conda-22.9.0               |   py39haa95532_0         888 KB
    conda-package-handling-1.9.0|   py39h8cc25b3_0         726 KB
    conda-repo-cli-1.0.20      |   py39haa95532_0         126 KB
    conda-token-0.4.0          |     pyhd3eb1b0_0          13 KB
    cryptography-38.0.1        |   py39h21b164f_0         991 KB
    cython-0.29.32             |   py39hd77b12b_0         1.7 MB
    daal4py-2021.6.0           |   py39h757b272_1      

In [3]:
import hnswlib
import numpy as np

dim = 16
num_elements = 10000

# Generating sample data
data = np.float32(np.random.random((num_elements, dim)))

# We split the data in two batches:
data1 = data[:num_elements // 2]
data2 = data[num_elements // 2:]

# Declaring index
p = hnswlib.Index(space='l2', dim=dim)  # possible options are l2, cosine or ip

# Initializing index
# max_elements - the maximum number of elements (capacity). Will throw an exception if exceeded
# during insertion of an element.
# The capacity can be increased by saving/loading the index, see below.
#
# ef_construction - controls index search speed/build speed tradeoff
#
# M - is tightly connected with internal dimensionality of the data. Strongly affects memory consumption (~M)
# Higher M leads to higher accuracy/run_time at fixed ef/efConstruction

p.init_index(max_elements=num_elements//2, ef_construction=100, M=16)

# Controlling the recall by setting ef:
# higher ef leads to better accuracy, but slower search
p.set_ef(10)

# Set number of threads used during batch search/construction
# By default using all available cores
p.set_num_threads(4)


print("Adding first batch of %d elements" % (len(data1)))
p.add_items(data1)

# Query the elements for themselves and measure recall:
labels, distances = p.knn_query(data1, k=1)
print("Recall for the first batch:", np.mean(labels.reshape(-1) == np.arange(len(data1))), "\n")

# Serializing and deleting the index:
index_path='first_half.bin'
print("Saving index to '%s'" % index_path)
p.save_index("first_half.bin")
del p

# Re-initializing, loading the index
p = hnswlib.Index(space='l2', dim=dim)  # the space can be changed - keeps the data, alters the distance function.

print("\nLoading index from 'first_half.bin'\n")

# Increase the total capacity (max_elements), so that it will handle the new data
p.load_index("first_half.bin", max_elements = num_elements)

print("Adding the second batch of %d elements" % (len(data2)))
p.add_items(data2)

# Query the elements for themselves and measure recall:
labels, distances = p.knn_query(data, k=1)
print("Recall for two batches:", np.mean(labels.reshape(-1) == np.arange(len(data))), "\n")

Adding first batch of 5000 elements
Recall for the first batch: 1.0 

Saving index to 'first_half.bin'

Loading index from 'first_half.bin'

Adding the second batch of 5000 elements
Recall for two batches: 1.0 



In [3]:
import numpy as np
d = 64                           # dimension
nb = 100000                      # database size
nq = 10000                       # nb of queries
np.random.seed(1234)             # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

imagecodecs-2021.8.2 | 6.0 MB    | #######9   |  79% 
imagecodecs-2021.8.2 | 6.0 MB    | ########1  |  81% 
imagecodecs-2021.8.2 | 6.0 MB    | ########2  |  83% 
imagecodecs-2021.8.2 | 6.0 MB    | ########5  |  85% 
imagecodecs-2021.8.2 | 6.0 MB    | ########6  |  87% 
imagecodecs-2021.8.2 | 6.0 MB    | ########8  |  88% 
imagecodecs-2021.8.2 | 6.0 MB    | #########  |  90% 
imagecodecs-2021.8.2 | 6.0 MB    | #########2 |  92% 
imagecodecs-2021.8.2 | 6.0 MB    | #########4 |  95% 
imagecodecs-2021.8.2 | 6.0 MB    | #########6 |  97% 
imagecodecs-2021.8.2 | 6.0 MB    | #########8 |  99% 
imagecodecs-2021.8.2 | 6.0 MB    | ########## | 100% 

conda-repo-cli-1.0.2 | 126 KB    |            |   0% 
conda-repo-cli-1.0.2 | 126 KB    | #2         |  13% 
conda-repo-cli-1.0.2 | 126 KB    | ##5        |  25% 
conda-repo-cli-1.0.2 | 126 KB    | ######3    |  63% 
conda-repo-cli-1.0.2 | 126 KB    | ########## | 100% 
conda-repo-cli-1.0.2 | 126 KB    | ########## | 100% 

pandas-1.4.4         | 8.7

In [4]:
import faiss                   # make faiss available
index = faiss.IndexFlatL2(d)   # build the index
print(index.is_trained)
index.add(xb)                  # add vectors to the index
print(index.ntotal)

True
100000


In [5]:
k = 4                          # we want to see 4 nearest neighbors
D, I = index.search(xb[:5], k) # sanity check
print(I)
print(D)
D, I = index.search(xq, k)     # actual search
print(I[:5])                   # neighbors of the 5 first queries
print(I[-5:])                  # neighbors of the 5 last queries

[[  0 393 363  78]
 [  1 555 277 364]
 [  2 304 101  13]
 [  3 173  18 182]
 [  4 288 370 531]]
[[0.        7.1751738 7.20763   7.2511625]
 [0.        6.3235645 6.684581  6.799946 ]
 [0.        5.7964087 6.391736  7.2815123]
 [0.        7.2779055 7.527987  7.6628466]
 [0.        6.7638035 7.2951202 7.3688145]]
[[ 381  207  210  477]
 [ 526  911  142   72]
 [ 838  527 1290  425]
 [ 196  184  164  359]
 [ 526  377  120  425]]
[[ 9900 10500  9309  9831]
 [11055 10895 10812 11321]
 [11353 11103 10164  9787]
 [10571 10664 10632  9638]
 [ 9628  9554 10036  9582]]
